### ISSUE TITLE
MAMAJNI 6.2.x: java.lang.NoSuchMethodError: onSuccess

### ISSUE THREAD

**Issue by maciejlach** [OpenMAMA/OpenMAMA#279]
# MAMAJNI 6.2.x: java.lang.NoSuchMethodError: onSuccess
## Summary
The OpenMAMA Java MamaPublisherJava sample (in 6.2.x), fail with the exception: `java.lang.NoSuchMethodError: onSuccess`.

## Areas Affected
- [ ] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [x] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [x] Examples

## Details
Exception occurs while starting the sample application:

```java
Exception in thread "main" java.lang.NoSuchMethodError: onSuccess
	at com.wombat.mama.MamaPublisher.initIDs(Native Method)
	at com.wombat.mama.MamaPublisher.<clinit>(MamaPublisher.java:31)
	at com.wombat.mama.examples.MamaPublisherJava.createPublisher(MamaPublisherJava.java:102)
	at com.wombat.mama.examples.MamaPublisherJava.run(MamaPublisherJava.java:248)
	at com.wombat.mama.examples.MamaPublisherJava.main(MamaPublisherJava.java:237)
```

Affected platforms: Win 10 x64, Centos 6 x64, Centos 7 x64.
OpenMAMA version: 6.2.0, 6.2.1-rc1.

Thise sample (plain OpenMAMA) works on 6.1.0 on Windows.

I was unable to install 6.1.0 package on Centos 6, due to broken dependency on:
```
Error: Package: openmama-6.1.0-1.el6.x86_64 (/openmama-6.1.0-1.el6.x86_64)
   Requires: libqpid-proton.so.7()(64bit)
```

Same issue arises in Centos 7:
```
Error: Package: openmama-6.1.0-1.el7.centos.x86_64 (/openmama-6.1.0-1.el7.centos.x86_64)
   Requires: libqpid-proton.so.7()(64bit)
```

**Comment by fquinner** [comment]
Unfortunately the qpid interface is pretty volatile and they keep changing their shared objects - the latest version with the latest RC is actually `libqpid-proton.so.10`. If you do a `yum update` and then install the RPM with yum, it should resolve and update the dependencies correctly for you on the installation side. Note that you may need the `epel-release` repo.

The onSuccess error I can recreate here looks like it was introduced in #256

**Comment by fquinner** [comment]
Just pushed a change in to next if you want to try our snapshot builds to verify? http://ci.openmama.org:8080/job/OpenMAMA_Snapshot_RPM/lastSuccessfulBuild/

**Comment by maciejlach** [comment]
Thank you for quick fix. The snapshot build allows to start publisher sample.
